controller_manager:
  ros__parameters:
    state_publish_rate: 50
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_link_to_link1
      - link1_to_link2
      - link2_to_link3
    command_interfaces:
      - position  
    state_interfaces:
      - position
      - velocity
